name: lexilearn
description: "A new Flutter project."

# Dòng sau ngăn không cho publish gói này lên pub.dev
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Các thư viện cần thiết
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  shared_preferences: ^2.5.3
  jwt_decoder: ^2.0.1
  percent_indicator: ^4.2.5
  riverpod: ^2.6.1
  flutter_riverpod: ^2.5.1
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.6

flutter_native_splash:
  android: true
  ios: trues
  color: "#D64151"
  image: assets/iconApp.png

flutter_launcher_icons:
  android: "launcher_icon"
  iOS: true
  image_path: "assets/iconApp.png"

flutter:
  uses-material-design: true

  assets:
    - assets/welcome.png
    - assets/welcome2.png
    - assets/Login.png
    - assets/iconApp.png
    - assets/icons/
    - assets/home/
    - assets/fonts/

  fonts:
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/Playfair_Display/static/PlayfairDisplay-ExtraBold.ttf
          weight: 800
    - family: Winky_Sans
      fonts:
        - asset: assets/fonts/Winky_Sans/static/WinkySans-ExtraBold.ttf
          weight: 800
